import type { ElementType, ReviewFrequency } from '@sf-manager/validation';
import { ReviewTemplate } from '../../domain/review-template.entity';
import { ReviewTemplateStatus } from '../../domain/review-template-status';

// Port (application layer, ADR-002/013): the review-template
// presentation/infrastructure layers (PR 9) depend on this interface, never
// on the Prisma adapter directly. See design.md Decision 5 / Interfaces —
// the concrete adapter is PrismaReviewTemplateRepository
// (infrastructure/persistence/prisma-review-template.repository.ts, PR 9).
//
// One question per selection entry, resolved through one of TWO distinct
// read paths (design.md Decision 5) — the frozen path MUST NOT reference
// "ChecklistQuestion" at all.
export interface TemplateQuestionEntry {
  questionId: string;
  order: number;
  text: string;
}

export interface TemplateWithQuestions {
  id: string;
  elementType: ElementType;
  frequency: ReviewFrequency;
  name: string;
  version: number | null;
  status: ReviewTemplateStatus;
  createdAt: Date;
  deletedAt: Date | null;
  questions: TemplateQuestionEntry[];
}

// design.md Data Flow — POST /review-templates/:id/activate, step 5:
// activate() runs ONE Serializable transaction (Decisions 3/4, PR 9) and
// returns the frozen version's own identity. Rejects with
// TransactionConflictError on P2034/P2002 (design.md Decision 3) — that
// rejection path is Phase 9's responsibility to implement in the adapter;
// this use case (PR 8) only calls activate() after its own pre-flight
// guards pass.
export interface ActivationOutcome {
  id: string;
  status: ReviewTemplateStatus;
  version: number;
}

export interface ReviewTemplateRepository {
  // Plain insert — status: draft, empty draftQuestionIds, deletedAt: null
  // (spec.md "Create Draft Template").
  create(template: ReviewTemplate): Promise<void>;

  // Default deletedAt: null filter (ADR-010) — an unknown id and a
  // soft-deleted id both resolve to null, one indistinguishable 404.
  findById(id: string): Promise<ReviewTemplate | null>;

  // Soft-deleted (drafts only — frozen versions are undeletable) templates
  // excluded by default (ADR-010; spec.md "Soft-deleted drafts excluded").
  // No question join — list responses carry metadata only (spec.md "List
  // and Read Templates").
  findAll(): Promise<ReviewTemplate[]>;

  // Decision 5 — draft path: resolves ordered question text through the
  // LIVE pool (ADR-010's soft-delete filter applies for free). Returns null
  // for an unknown/soft-deleted/non-draft id.
  findDraftWithLiveQuestions(id: string): Promise<TemplateWithQuestions | null>;

  // Decision 5 — frozen path: reads ONLY the persisted
  // ReviewTemplateQuestion snapshot rows. This query MUST NOT reference
  // "ChecklistQuestion". Returns null for an unknown/non-frozen id.
  findFrozenWithSnapshot(id: string): Promise<TemplateWithQuestions | null>;

  // Full-replace semantics (spec.md "Replacing the selection is a full
  // replace, not a merge") — the submitted order becomes each entry's
  // `order`. Returns whether a draft row was actually found and replaced.
  replaceDraftQuestions(id: string, questionIds: string[]): Promise<boolean>;

  // Decision 3/4 (PR 9) — ONE Serializable transaction: assign version,
  // snapshot INSERT...SELECT, retire predecessor, freeze. `rowIds` are
  // app-generated UUIDv7s (ADR-009), one per selected question, generated by
  // the use case before this call.
  activate(id: string, rowIds: string[]): Promise<ActivationOutcome>;

  // Sets deletedAt on a draft only (spec.md "Only Drafts May Be Soft-
  // Deleted"). Returns whether the row was actually transitioned.
  softDeleteDraftById(id: string): Promise<boolean>;
}

export const REVIEW_TEMPLATE_REPOSITORY = Symbol('REVIEW_TEMPLATE_REPOSITORY');
