import { User } from '../../domain/user.entity';

// Port (application layer, ADR-002/013): the `auth` module (PR 3) and
// `prisma/seed.ts` (PR 3) depend on this interface, never on the Prisma
// adapter directly. See design.md Decision 1/9 and Interfaces/Contracts —
// the concrete adapter is PrismaUserRepository
// (infrastructure/persistence/prisma-user.repository.ts).
export interface UserRepository {
  // Default `deletedAt: null` filter (ADR-010) — a soft-deleted user is
  // treated as not found, so callers (e.g. LoginUseCase) get an identical
  // "not found" outcome for wrong password and soft-deleted accounts alike.
  findByEmail(email: string): Promise<User | null>;

  // Upsert by unique email. On the UPDATE path (email already exists), the
  // existing row's `id` is PRESERVED — a fresh id generated by the caller
  // (e.g. seed.ts on every run) never overwrites the original identity
  // (ADR-009). Not exposed via any controller — FR-003 CRUD is a later
  // slice.
  save(user: User): Promise<void>;
}

export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
