import { Role } from '../../domain/role';
import { User } from '../../domain/user.entity';

// Port (application layer, ADR-002/013): the `auth` module (PR 3) and
// `prisma/seed.ts` (PR 3) depend on this interface, never on the Prisma
// adapter directly. See design.md Decision 1/9 and Interfaces/Contracts —
// the concrete adapter is PrismaUserRepository
// (infrastructure/persistence/prisma-user.repository.ts).
export interface UserRepository {
  // Default `deletedAt: null` filter (ADR-010) — a soft-deleted user is
  // treated as not found, so callers (e.g. LoginUseCase) get an identical
  // "not found" outcome for wrong password and soft-deleted accounts alike.
  findByEmail(email: string): Promise<User | null>;

  // Upsert by unique email. On the UPDATE path (email already exists), the
  // existing row's `id` is PRESERVED — a fresh id generated by the caller
  // (e.g. seed.ts on every run) never overwrites the original identity
  // (ADR-009). Kept ONLY for `prisma/seed.ts` (design.md Decision 8) — never
  // exposed via any controller; `POST /users` uses `create()` below.
  save(user: User): Promise<void>;

  // --- Additions below: design.md Decision 8, Decision 10, Interfaces/
  // Contracts (PR 5 — Users application: repo port + 4 use cases).

  // Same default `deletedAt: null` filter as findByEmail (ADR-010) — a
  // soft-deleted user resolves to null, so Update/Deactivate use cases 404
  // it the same way as "no such user", never "already deleted".
  findById(id: string): Promise<User | null>;

  // Soft-deleted users are EXCLUDED — no flag, no options arg (design.md
  // Decision 10). Adapter: findMany({ where: this.withDefaultFilter({}) }),
  // exactly like findByEmail.
  findAll(): Promise<User[]>;

  // Plain insert (design.md Decision 8) — distinct from save()'s upsert. A
  // unique-email violation (schema.prisma: `email` is a plain @unique index,
  // not scoped to active rows, so it also blocks against a soft-deleted
  // row with the same email) surfaces as EmailAlreadyInUseError; it must
  // never silently overwrite an existing user's role or password hash.
  create(user: User): Promise<void>;

  updateById(
    id: string,
    changes: { email?: string; role?: Role },
  ): Promise<void>;

  // Sets deletedAt (ADR-010) — no row deletion.
  softDeleteById(id: string): Promise<void>;

  countActiveByRole(role: Role): Promise<number>;

  // MUST run at an isolation level that prevents write skew (adapter:
  // Prisma `$transaction({ isolationLevel: 'Serializable' })`, design.md
  // Decision 3) so two concurrent transactions each demoting/deactivating
  // one of the last two SYSTEM_ADMIN users can't both observe "one admin
  // left" and both commit. A `work` callback that throws MUST roll back; a
  // concurrency abort (Prisma P2034) surfaces as a conflict to the caller.
  transactional<T>(work: (repo: UserRepository) => Promise<T>): Promise<T>;
}

export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
