import { Inject, Injectable } from '@nestjs/common';
import {
  USER_REPOSITORY,
  type UserRepository,
} from '../../../users/application/ports/user.repository.port';
import { InvalidCredentialsError } from '../../domain/invalid-credentials.error';
import {
  PASSWORD_HASHER,
  type PasswordHasher,
} from '../../../../shared/application/ports/password-hasher.port';
import {
  TOKEN_DENYLIST,
  type TokenDenylist,
} from '../ports/token-denylist.port';
import { TOKEN_ISSUER, type TokenIssuer } from '../ports/token-issuer.port';

export interface LoginResult {
  user: { id: string; email: string };
  accessToken: string;
}

// design.md Data Flow (POST /auth/login) + Decisions 7, 9, 10.
@Injectable()
export class LoginUseCase {
  constructor(
    @Inject(USER_REPOSITORY) private readonly userRepository: UserRepository,
    @Inject(PASSWORD_HASHER) private readonly passwordHasher: PasswordHasher,
    @Inject(TOKEN_ISSUER) private readonly tokenIssuer: TokenIssuer,
    @Inject(TOKEN_DENYLIST) private readonly tokenDenylist: TokenDenylist,
  ) {}

  async execute(email: string, password: string): Promise<LoginResult> {
    // Default deletedAt: null filter (ADR-010) already applied by the
    // repository — a soft-deleted user resolves to null here, identical to
    // an unknown email (Decision 7).
    const user = await this.userRepository.findByEmail(email);

    // Timing-mitigation (Decision 10): when no user was found, still run a
    // comparably-costed argon2id verify against a fixed dummy hash instead
    // of failing immediately, so the response time doesn't leak whether the
    // email exists. A rejection from the hashing library itself (e.g. a
    // corrupt/malformed hash string) is treated as a failed verification,
    // not an unhandled exception — it must not leak a distinguishable
    // failure signal (500 vs 401) about hash corruption.
    let isValid: boolean;
    try {
      isValid = user
        ? await this.passwordHasher.verify(user.passwordHash, password)
        : await this.passwordHasher.verifyAgainstDummy(password);
    } catch {
      isValid = false;
    }

    if (!user || !isValid) {
      throw new InvalidCredentialsError();
    }

    // Only after a successful login — never on a failed attempt, so a
    // brute-force run against this endpoint doesn't also hammer the
    // denylist table with cleanup queries (design.md Data Flow).
    // Purely opportunistic housekeeping — a rejection here (e.g. transient
    // DB error) must never gate an otherwise-successful login; a failed
    // cleanup just means stale rows linger a bit longer, which is harmless.
    try {
      await this.tokenDenylist.deleteExpired();
    } catch {
      // swallow: best-effort cleanup, not a security-relevant operation.
    }

    // jti is generated by the TokenIssuer adapter itself (uuid v4(),
    // deliberately NOT the IdGenerator/UUIDv7 port used for entity ids —
    // Decision 9), not by this use case.
    const accessToken = await this.tokenIssuer.sign({
      sub: user.id,
      email: user.email,
    });

    return { user: { id: user.id, email: user.email }, accessToken };
  }
}
